### ISSUE TITLE
workshop addon page has no link to this repo

### ISSUE THREAD

**Issue by mykola2312** [Xalalau/mingenet#1]
I had to dive into addon files to find this github repo, as well as lua code. Why don't put it into workshop for faster access?

**Comment by KptYusuf** [comment]
i have question how do i use mingenet

**Comment by Xalalau** [comment]
> I had to dive into addon files to find this github repo, as well as lua code. Why don't put it into workshop for faster access?

I'm keeping it more or less hidden because I don't like how the system is implemented. I should've used Redis or Memcached instead of the MySQL memory engine.

> i have question how do i use mingenet

Upload it to a webserver. You can use MySQL or MariaDB to host the databse (the sql file in the sqlbackup folder) and Nginx or Apache to host the website itself.

Mingenet works by organizing queues on time intervals defined by the endpoint calls theirselves. It needs my Lua lobby code, which is embedded in gm_construct 13 beta with some documentation.
